### ISSUE TITLE
csgostats command randomly not working

### ISSUE THREAD

**Issue by RussellChien** [ericpretzel/wid-bot#40]
the csgostats command seems to not work for no reason even though the user has a valid csgostats profile.

**Comment by erakai** [comment]
To provide more information, using the /csgostats command will randomly return "An error occurred." with no elaboration rather than the stats. This happens randomly regardless of if you use a url or a profile name.

Image:
![image](https://user-images.githubusercontent.com/42708589/183813468-75c35187-ff01-4454-84cb-0f3d941f3394.png)

To recreate this:
1. Get a random bunch of csgo profiles
2. Run /csgostats [url] on all of them
3. Be disappointed

**Comment by ericpretzel** [comment]
@hirodnazari are you 100% sure there is no error log output for this
